DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS query;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL
);

CREATE TABLE query (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  content TEXT NOT NULL,
  answered BOOLEAN NOT NULL DEFAULT FALSE,
  answer TEXT,
  FOREIGN KEY (author_id) REFERENCES user (id)
);